
name: Testing with jest
on: 
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
env: # Or as an environment variable
  HOLODEX_API_KEY: ${{ secrets.HOLODEX_API_KEY }}

jobs:
  test-the-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run tests
      run: npx jest

